{
  description = "inferno";

  nixConfig = {
    # These are required to build the project, otherwise GHC will be built from
    # source (this is not always possible using haskell.nix either), so it makes
    # sense to enable them directly in the flake
    extra-substituters = [ "https://cache.iog.io" ];
    extra-trusted-public-keys = [
      "hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ="
    ];
    bash-prompt = "\\[\\e[0;37m\\](\\[\\e[0m\\]nix) \\[\\e[0;1;91m\\]inferno \\[\\e[0m\\]\\w \\[\\e[0;1m\\]λ \\[\\e[0m\\]";
  };

  inputs = {
    nixpkgs.follows = "haskell-nix/nixpkgs-unstable";
    flake-parts.url = "github:hercules-ci/flake-parts";
    treefmt.url = "github:numtide/treefmt";
    # haskell.nix has far better support for multi-component projects, so it's
    # preferable over nixpkgs' Haskell support
    haskell-nix.url = "github:input-output-hk/haskell.nix";
    npm-buildpackage.url = "github:serokell/nix-npm-buildpackage";
    flake-compat = {
      url = "github:edolstra/flake-compat";
      flake = false;
    };
  };

  outputs =
    { self
    , nixpkgs
    , flake-parts
    , treefmt
    , haskell-nix
    , ...
    }@inputs:
    let
      inherit (nixpkgs) lib;

      defaultCompiler = "ghc924";

      # Takes an attribute set mapping compiler versions to `flake`s generated
      # by `haskell.nix` (see `flakesFor` above) and suffixes each derivation
      # in all flake outputs selected by `attr` with the corresponding compiler
      # version, then flattens the resulting structure to combine all derivations
      # into a single set
      #
      #    collectOutputs
      #      "checks"
      #      {
      #        ghc8107 = { checks = { x:y:z = <drv>; }; };
      #        ghc922 = { checks = { x:y:z = <drv>; }; };
      #      }
      #
      # => { x:y:z-ghc8107 = <drv>; x:y:z-ghc922 = <drv>; }
      collectOutputs = attr: flakes:
        let
          outputsByCompiler = lib.mapAttrsToList
            (compiler: flake: { "${compiler}" = flake.${attr} or { }; })
            flakes;
          addSuffix = compiler: lib.attrsets.mapAttrs'
            (output: drv:
              lib.attrsets.nameValuePair "${output}-${compiler}" drv
            );
          withSuffixes = builtins.map
            (builtins.mapAttrs addSuffix)
            outputsByCompiler;
          justOutputs = builtins.concatMap builtins.attrValues withSuffixes;
        in
        builtins.foldl' (x: y: x // y) { } justOutputs;

      # Everything related to the haskell.nix project needs to be defined here
      # in order to be used by both the system-enumerated outputs (`packages`,
      # `devShells`, etc, ...) and the non-enumerated ones (`overlays`, etc...).
      # This also means that everything needs to be parameterized by `pkgs`

      # Get the autogenerated flake outputs from `haskell.nix`, for different
      # GHC versions
      flakesFor = pkgs: builtins.listToAttrs
        (
          # only GHC 8.10.7 or newer is supported on M1 Macs
          lib.lists.forEach ([ defaultCompiler ] ++ lib.optional (pkgs.system != "aarch64-darwin") "ghc884")
            (compiler: lib.attrsets.nameValuePair
              compiler
              # TODO
              # Do we want to enable any `crossPlatforms` here?
              ((infernoFor compiler pkgs).flake { })
            )
        );

      # This should be parameterized by the `pkgs` used to build the project. We
      # want users who get packages from our `overlays.default` to be able to
      # use their own `nixpkgs` without having to instantiate ours as well
      # (which would happen if we just use `self.packages` directly in the overlay)
      infernoFor = compiler: pkgs: pkgs.haskell-nix.cabalProject {
        name = "inferno";
        compiler-nix-name = compiler;
        src = builtins.path {
          path = ./.;
          filter = path: type:
            builtins.any
              (ext: baseNameOf path != ext)
              [ ".nix" ".md" ];
        };
        shell = {
          withHoogle = true;
          tools = {
            cabal = { };
            haskell-language-server = { };
          };
          buildInputs = [ pkgs.nixpkgs-fmt ] ++ 
            # ormolu build currently segfaults on the M1
            lib.optional (pkgs.system != "aarch64-darwin") (ormoluFor compiler pkgs);
        };
        modules = [
          {
            packages = {
              # This takes forever to build
              ghc.components.library.doHaddock = false;
            };
          }
        ];
      };

      # Get the same version of `ormolu` everywhere, including the shell
      ormoluFor = compiler: pkgs: pkgs.haskell-nix.tool
        compiler "ormolu" "0.5.0.1";

      # Inferno's VSCode packages
      vsCodeInfernoFor = pkgs:
        {
          vscode-inferno-syntax-highlighting = pkgs.buildNpmPackage {
            src = ./vscode-inferno-syntax-highlighting;
            npmBuild = ''
              npm run build-tm
              vsce package
              npm run build-monarch
            '';
            installPhase = ''
              mkdir $out
              cp *.vsix $out
              cp syntaxes/inferno.monarch.json $out
            '';
          };
          vscode-inferno-lsp-server = pkgs.buildNpmPackage {
            src = ./vscode-inferno-lsp-server;
            nativeBuildInputs = [ pkgs.nodePackages.typescript ];
            npmBuild = ''
              npm run package
            '';
            installPhase = "mkdir $out && cp *.vsix $out";
          };
        };

    in
    flake-parts.lib.mkFlake { inherit self; } {
      systems = nixpkgs.lib.systems.flakeExposed;
      # Outputs that are enumerated by system
      perSystem = { config, pkgs, lib, system, ... }:
        let
          flakes = flakesFor pkgs;
        in
        {
          # Set the `pkgs` that are passed to `perSystem`
          _module.args.pkgs = import nixpkgs {
            inherit (haskell-nix) config;
            inherit system;
            overlays = [
              haskell-nix.overlays.combined
              inputs.npm-buildpackage.overlays.default
            ];
          };

          # To enter a development environment for a particular GHC version, use
          # the compiler name, e.g. `nix develop .#ghc8107`
          devShells =
            lib.attrsets.mapAttrs'
              (compiler: v: lib.attrsets.nameValuePair compiler v.devShell)
              flakes
            // { default = flakes.${defaultCompiler}.devShell; };

          packages =
            let
              inherit (flakes.${defaultCompiler}) packages;
              # All of the packages for each compiler version, plus the VSCode
              # packages
              ps =
                collectOutputs "packages" flakes // {
                  inherit (vsCodeInfernoFor pkgs)
                    vscode-inferno-syntax-highlighting
                    vscode-inferno-lsp-server;
                  inferno-lsp-server = packages."inferno-lsp:exe:inferno-lsp-server";
                };
            in
            ps // {
              # Build all packages and checks
              default = pkgs.runCommand "check"
                {
                  combined = builtins.attrValues self.checks.${system}
                  ++ builtins.attrValues ps;
                }
                ''
                  echo $combined
                  touch $out
                '';
            };

          apps =
            let
              inherit (flakes.${defaultCompiler}) apps;
            in
            {
              inferno-lsp-server = apps."inferno-lsp:exe:inferno-lsp-server";
            } // collectOutputs "apps" flakes;

          # Usage: `nix build .#checks.<SYSTEM>.<check>`, e.g.
          #
          # `nix build .#checks.x86_64-linux.inferno-core:test:inferno-tests`
          #
          # To run a check for a particular compiler version, suffix the derivation
          # name with the GHC version, e.g.
          #
          # `nix build .#checks.x86_64-linux.inferno-core:test:inferno-tests-ghc924`
          checks =
            {
              formatting = pkgs.runCommand "formatting-check"
                {
                  buildInputs = [ pkgs.nixpkgs-fmt (ormoluFor defaultCompiler pkgs) ];
                }
                ''
                  cp -r --no-preserve=mode --preserve=timestamps ${self}/* .
                  chmod -R +rwx .
                  export HOME=$TMPDIR
                  ${treefmt.legacyPackages.${system}.treefmt}/bin/treefmt --fail-on-change
                  touch $out
                '';
            }
            // flakes.${defaultCompiler}.checks
            // collectOutputs "checks" flakes;

          # NOTE
          # This should be run from the development shell (i.e. run `nix develop` first).
          # Treefmt expects the formatters to be on the PATH
          formatter = treefmt.legacyPackages.${system}.withConfig {
            settings = lib.importTOML ./treefmt.toml;
            projectRootFile = "flake.nix";
          };
        };

      # Non-enumerated outputs
      flake = {
        overlays.default = lib.composeManyExtensions [
          (final: prev:
            # Needed to build the VSCode packages
            lib.optionalAttrs (!(prev ? buildNpmPackage))
              (inputs.npm-buildpackage.overlays.default final prev)
            # Needed to build Inferno itself
            // lib.optionalAttrs (!(prev ? haskell-nix))
              (inputs.haskell-nix.overlays.combined final prev)
          )
          (_: prev:
            let
              inherit ((flakesFor prev).${defaultCompiler}) packages;
            in
            {
              inherit
                (vsCodeInfernoFor prev)
                vscode-inferno-syntax-highlighting
                vscode-inferno-lsp-server;
              inferno-lsp-server = packages."inferno-lsp:exe:inferno-lsp-server";
            }
          )
        ];
      };
    };
}
